pipeline {
    agent any

    tools {
        nodejs 'NodeJS 20'
    }

    environment {
        NODE_ENV = 'test'
    }

    stages {

        stage('Install Backend Dependencies') {
            steps {
                dir('eventflow/backend') {
                    bat 'npm install'
                }
            }
        }

        stage('Run Backend Tests') {
            steps {
                dir('eventflow/backend') {
                    bat 'npm test'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {

                script {

                    def scannerHome = tool 'SonarScanner'

                    withSonarQubeEnv('SonarQube') {

                        dir('eventflow/backend') {

                            bat "${scannerHome}\\bin\\sonar-scanner.bat"
                        }
                    }
                }
            }
        }

        stage('Build Docker Images') {
            steps {

                bat 'docker build -t eventflow-backend ./eventflow/backend'

                bat 'docker build -t eventflow-frontend ./eventflow/frontend'
            }
        }

        // stage('Deploy to Kubernetes') {
        //     steps {
        //         bat 'kubectl apply -f eventflow/k8s/'
        //     }
        // }
    }
}