sonar.projectKey=eventflow
sonar.projectName=eventFlow
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=tests

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=node_modules/**

sonar.typescript.tsconfigPath=tsconfig.json